name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21', '1.22']
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Get dependencies
      run: go get -v -t -d ./...

    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        # Optional coverage threshold
        # use fail-coverage to determine what should happen below this threshold
        coverage-threshold: 99.999999

        # collect coverage for all packages beyond the one under test
        cover-pkg: ./...
